var default_x = 32;
var default_y = 56;
// sprite_change_offset("idle_hurtbox", default_x, default_y);
sprite_change_offset("mask", default_x, default_y);
sprite_change_offset("idle", default_x, default_y);
sprite_change_offset("hurt", default_x, default_y);
sprite_change_offset("crouch", default_x, default_y);
sprite_change_offset("walk", default_x, default_y);
sprite_change_offset("walkturn", default_x, default_y);
sprite_change_offset("dash", default_x, default_y);
sprite_change_offset("dashstart", default_x, default_y);
sprite_change_offset("dashstop", default_x, default_y);
sprite_change_offset("dashturn", default_x, default_y);

sprite_change_offset("jumpstart", default_x, default_y);
sprite_change_offset("jump", default_x, default_y);
sprite_change_offset("doublejump", default_x,default_y);
sprite_change_offset("walljump", default_x, default_y);
sprite_change_offset("pratfall", default_x, default_y);
sprite_change_offset("land", default_x, default_y);
sprite_change_offset("landinglag", default_x, default_y);

sprite_change_offset("parry", default_x, default_y);
sprite_change_offset("roll_forward", default_x, default_y);
sprite_change_offset("roll_backward", default_x, default_y);
sprite_change_offset("airdodge", default_x, default_y);
sprite_change_offset("waveland", default_x, default_y);
sprite_change_offset("tech", default_x, default_y);

sprite_change_offset("jab", default_x, default_y);
sprite_change_offset("dattack", default_x, 72);
sprite_change_offset("ftilt", default_x, default_y);
sprite_change_offset("dtilt", default_x, default_y);
sprite_change_offset("utilt", default_x, default_y);
sprite_change_offset("nair", default_x, default_y);
sprite_change_offset("fair", default_x, default_y);
sprite_change_offset("bair", default_x, default_y);
sprite_change_offset("uair", default_x, default_y);
sprite_change_offset("dair", default_x, default_y);
sprite_change_offset("fstrong", default_x, 72);
sprite_change_offset("ustrong", default_x, default_y);
sprite_change_offset("dstrong", default_x, 72);
sprite_change_offset("nspecial", default_x, default_y);
sprite_change_offset("nspecial_air", default_x, default_y);
sprite_change_offset("fspecial", default_x, default_y);
sprite_change_offset("fspecial_air", default_x, default_y);
sprite_change_offset("uspecial", default_x, default_y);
sprite_change_offset("uspecial_air", default_x, default_y);
sprite_change_offset("dspecial", default_x, default_y);
sprite_change_offset("dspecial_air", default_x, default_y);
sprite_change_offset("taunt", default_x, default_y);

sprite_change_offset("plat", default_x, 0);

sprite_change_offset("blackbox", 80, 80);
sprite_change_offset("blackbox_mask", 80, 80);
sprite_change_offset("charges", 15, 14);
sprite_change_offset("mailbox", default_x, default_x);
sprite_change_offset("mailbox_mask", default_x, default_x);
sprite_change_offset("mailflag", 0, 32);
sprite_change_offset("mail_icon", 32, 32);
sprite_change_offset("jackbox", 32, 32);
sprite_change_offset("jackbox_mask", 16, 32);